//loadInfo = "<h1>将 HMCL 放在U盘上，插上U盘就能开van</h1><h3>下载 Java</h3><p>与硬盘中安装不同，由于不同电脑安装 Java 的情况不同，因此我们需要在U盘中部署免安装版的 Java。</p><p>下载教程：<a href='item.html?proFile=java/java.js'>下载和安装 Java</a><h3>配置启动器</h3>"
//loadInfo = "<h1>将 HMCL 放在U盘上，插上U盘就能开van</h1><p>抱歉，此文章仍在编写，敬请期待！</p>"
var hmclCfg1 = hmclCfg2 = false;
var usd = true;
var hmclCfg = loadJS(srcFnt + "hmclCfg.js");
var checkInfo = function(){
    if(hmclCfg1 && hmclCfg2){
        loadInfo = "<h1>将 HMCL 放在U盘上，插上U盘就能开van</h1><h3>下载 HMCL (Windows)</h3><p>访问 HMCL 官网：<a href='https://hmcl.huangyuhui.net/download/'>showLink</a>，找到“下载开发版”（由于稳定版下载通道为需要登录且限速的垃圾城通网盘，所以不推荐下载），<b>点击“.jar”格式的文件下载</b>。</p><div class='imgTips'><img src='./DnFromOfficial.png'/><div style='top:91.5%;left:25%;font-size:30px;font-weight:bolder'><<点此下载</div></div><p>又或者通过无所不能的 GitHub 下载，打开链接：<a href='https://github.com/huanghongxun/HMCL/releases'>showLink</a>（可能需要梯子），其中在标题开头有“release”字样的则是稳定版，否则就是开发版。找到带有“Latest”标志的版本 (最新版)，在“Assets”中<b>找到“.jar”后缀的文件</b>，点击下载。</p><img src='./HMCLDnJAR.gif'/><h3>下载U盘辅助脚本</h3><p>由于 HMCL 默认只检测系统中已经安装的Java，且将数据存放到了系统中，因此需要使用辅助脚本文件使其在U盘文件夹中存放数据或检测 Java。这个辅助脚本其实是我自己写的，耗费了我114.5小时的时间来编写，功能丰富，希望大家能到B站多多支持一下我q(≧▽≦q)，介绍视频见B站：未发布</p><p>首先访问<a href='itemDir/../../HHMLDocs/cn.js'>HHML辅助脚本的文档</a>，在“简单用法”中点击任意一个下载：</p><img src='./HHMLDn.gif'/><p>注意：如果你的系统启用了“使用 UTF-8 提供全球语言支持”，<b>请一定要使用英文版，否则会乱码闪退！</b></p><img src='./UTF8Enabled.png'/><h3>配置 Java 和 HMCL（无需安装）</h3><p>与其他启动器不同的是，HMCL 启动器主体也基于 Java 开发，这意味着需要在进入启动器之前就必须将 Java 配置好。不过在U盘上不要使用安装包（installer）安装，<b>应该选择无需安装的压缩包（archive）</b>，下载教程见：<a href='itemDir/../java/java.js'>Java 下载和安装指南</a></p><p>来到U盘这边，新建一个空文件夹，然后把上一步下载的 HMCL JAR 和辅助脚本放进去。</p><img src='./HMCLUMkDir.gif'/><p>然后把下载的 Java 压缩包里面的文件夹解压到这个文件夹，如果你需要多个 Java 版本，也可以解压多个进去，辅助脚本会自动检测。</p><img src='./UAddJava.gif'/><p><b>启动方式：打开辅助脚本（HHML-xxxxx.bat），在闪一段代码后，HMCL 就会启动</b>。（如果卡在搜索 Java 这一步很长时间不要问我，问就是你U盘太拉）初次启动可能需要下载依赖库，请确保网络环境良好。</p><img src='./ULaunch.gif'/><p>但有时候也会抛出如下错误，一般关闭再重新打开即可，如果还是不行请检查网络环境。</p><img src='./HMCLDepErr.png'/><p>依赖库下载完成后便会进入主界面，点击“同意”同意用户协议。</p>" + hmclCfg1 + "<p>如果是U盘游玩，记得要把“.minecraft”文件夹放到U盘中，并启用“若可能，游戏目录使用相对路径”，因为U盘的盘符（G:\\ H:\\ 等）在不同电脑或系统上会产生变化，导致游戏路径失效。</p><div class='imgTips'><img src='./HMCLEnableRelatively.gif'/><div style='top:31%;left:25%;font-size:20px;font-weight:bolder'><<开启相对路径后，可忽视游戏路径中的盘符</div></div>" + hmclCfg2 + "<h3>启动速度慢得离谱</h3><p>HMCL 在启动游戏时会检查文件完整性，受限于U盘性能这会花费很多时间：</p><div class='imgTips'><img src='./HMCLChkFile.png'/><div style='top:29%;left:38%;font-size:24px;font-weight:bolder'>在U盘上这一步要卡很久</div></div><p>可以在全局设置和游戏特定设置中找到高级设置，开启“不检查游戏完整性”，之后启动速度就恢复正常了。</p><img src='./HMCLDisableChk.gif'/><h3>退出启动器</h3><p>在关闭 HMCL 和游戏后，命令行窗口会再次出现，第一次启动辅助脚本会将运行时备份到U盘以备在下一台电脑上启动无需重新下载，之后可能会询问是否备份全局配置，按任意键继续，否则下次启动账号和部分设置会复原。（如果没有询问窗口自动关闭，则是已经自动备份）</p><img src='./HHMLExit.gif'/>";
    } else setTimeout(function(){checkInfo()},0);
}
checkInfo();